language: php

php:
  - 5.5
  - 5.6
services:
  - mysql

before_script:
  - composer self-update
  - composer update
  - mysql -e 'create database cargo_sample;'
  - mysql -uroot cargo_sample < ./scripts/cargo_sample.sql
  - cp ./config/local.config.php.dist ./config/local.config.php
  - cp ./config/behat.yml.travis ./config/behat.yml
  - chmod -R 777 ./data/cache
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "java -jar selenium-server-standalone-2.46.0.jar > /dev/null &"
  # webserver setup
  -  php -S 0.0.0.0:8000 -t public/ &
  - sleep 10


script:
  - php ./bin/phpunit -c ./CargoBackend/tests
  - php ./bin/phpunit -c ./GraphTraversalService/tests
  - bin/behat --verbose

